"""add_contextual_chain_tracking

Revision ID: 56820dcb6bd7
Revises: 
Create Date: 2026-02-15 17:06:23.116121+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56820dcb6bd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contextual_chain_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('parent_nodes', sa.JSON(), nullable=False),
    sa.Column('node_metadata', sa.JSON(), nullable=False),
    sa.Column('lathering_depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_type_depth', 'contextual_chain_nodes', ['node_type', 'lathering_depth'], unique=False)
    op.create_index(op.f('ix_contextual_chain_nodes_id'), 'contextual_chain_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_contextual_chain_nodes_lathering_depth'), 'contextual_chain_nodes', ['lathering_depth'], unique=False)
    op.create_index(op.f('ix_contextual_chain_nodes_node_id'), 'contextual_chain_nodes', ['node_id'], unique=True)
    op.create_index(op.f('ix_contextual_chain_nodes_node_type'), 'contextual_chain_nodes', ['node_type'], unique=False)
    op.create_table('heritage_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ancestor_node_id', sa.String(length=100), nullable=False),
    sa.Column('descendant_node_id', sa.String(length=100), nullable=False),
    sa.Column('depth_distance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ancestor_descendant', 'heritage_lineage', ['ancestor_node_id', 'descendant_node_id'], unique=True)
    op.create_index('idx_descendant_depth', 'heritage_lineage', ['descendant_node_id', 'depth_distance'], unique=False)
    op.create_index(op.f('ix_heritage_lineage_ancestor_node_id'), 'heritage_lineage', ['ancestor_node_id'], unique=False)
    op.create_index(op.f('ix_heritage_lineage_descendant_node_id'), 'heritage_lineage', ['descendant_node_id'], unique=False)
    op.create_index(op.f('ix_heritage_lineage_id'), 'heritage_lineage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heritage_lineage_id'), table_name='heritage_lineage')
    op.drop_index(op.f('ix_heritage_lineage_descendant_node_id'), table_name='heritage_lineage')
    op.drop_index(op.f('ix_heritage_lineage_ancestor_node_id'), table_name='heritage_lineage')
    op.drop_index('idx_descendant_depth', table_name='heritage_lineage')
    op.drop_index('idx_ancestor_descendant', table_name='heritage_lineage')
    op.drop_table('heritage_lineage')
    op.drop_index(op.f('ix_contextual_chain_nodes_node_type'), table_name='contextual_chain_nodes')
    op.drop_index(op.f('ix_contextual_chain_nodes_node_id'), table_name='contextual_chain_nodes')
    op.drop_index(op.f('ix_contextual_chain_nodes_lathering_depth'), table_name='contextual_chain_nodes')
    op.drop_index(op.f('ix_contextual_chain_nodes_id'), table_name='contextual_chain_nodes')
    op.drop_index('idx_node_type_depth', table_name='contextual_chain_nodes')
    op.drop_table('contextual_chain_nodes')
    # ### end Alembic commands ###
